document.addEventListener('DOMContentLoaded',()=>{
 const header=document.getElementById('site-header'), nav=document.getElementById('nav'), toggle=document.getElementById('nav-toggle'), top=document.getElementById('back-top'), progress=document.getElementById('page-progress');
 toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('active');toggle.setAttribute('aria-expanded',open)});
 nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('active');toggle?.setAttribute('aria-expanded','false')}));
 const reveals=document.querySelectorAll('.reveal');
 const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');io.unobserve(e.target)}}),{threshold:.12}); reveals.forEach(x=>io.observe(x));
 const counters=document.querySelectorAll('[data-count]');
 const countIO=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=Number(el.dataset.count);const plus=el.textContent.includes('+');const duration=900,start=performance.now();function tick(now){const p=Math.min((now-start)/duration,1),v=Math.floor(end*(1-Math.pow(1-p,3)));el.textContent=(v>=1000?v.toLocaleString():v)+(plus?'+':'');if(p<1)requestAnimationFrame(tick);else el.textContent=(end>=1000?end.toLocaleString():end)+(plus?'+':'')}requestAnimationFrame(tick);countIO.unobserve(el)}),{threshold:.8}); counters.forEach(x=>countIO.observe(x));
 window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>30);top.classList.toggle('show',scrollY>600);const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=max>0?(scrollY/max*100)+'%':'0%';const sections=[...document.querySelectorAll('main section[id]')];let current='';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});nav?.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))},{passive:true});
 top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
 const hero=document.querySelector('.hero-visual'); if(hero&&!matchMedia('(prefers-reduced-motion: reduce)').matches){hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;hero.querySelector('.portrait-wrap').style.transform=`translate(${x*8}px,${y*6}px)`;hero.querySelectorAll('.node').forEach((n,i)=>n.style.transform=`translate(${x*(i%2?4:-4)}px,${y*3}px)`)});hero.addEventListener('pointerleave',()=>{hero.querySelector('.portrait-wrap').style.transform='';hero.querySelectorAll('.node').forEach(n=>n.style.transform='')})}
});
